@startuml
title Admin Activity
start
:Login;
fork
  :View Registrations;
  :Verify Documents;
  if (Documents OK?) then (yes)
    :Accept Registration;
else (no)
    :Cancel Registration;
endif
fork again
  :View Programs;
  fork
  :Add Program;
  fork again
  :Update Program;
  fork again
  :Delete Program;
  end fork
fork again
  :View Courses;
  fork
  :Add Course;
  fork again
  :Update Course;
  fork again
  :Delete Course;
  end fork

end fork
stop
@enduml