@startuml
title Student Activity
|Student|
start
:Visit Platform;
if (Has Account?) then (yes)
    :Sign In;
else (no)
    :Sign Up;
    :Sign In;
endif
:Welcome Screen;
:View Programs;
:Select Program;
:View Program Details;
:Register for Program;
if (Already Registered?) then (yes)
    :Display Error;
else (no)
    :Upload Documents;
    |Admin|
    :Verify Registration;
|Student|
endif

:View Profile;
if (Registration Verified?) then (yes)
    :Pay Registration Fee;
    :Payment Confirmation;
endif
stop
@enduml